CREATE DATABASE RECOMENDACAO;

USE RECOMENDACAO;

CREATE TABLE USUARIO(
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_USUARIO VARCHAR(30),
	SENHA_USUARIO VARCHAR(12),
	NOTA FLOAT(5,5)
);


INSERT INTO USUARIO VALUES(NULL,'Ana Claudia','******', 2.5);
INSERT INTO USUARIO VALUES(NULL,'Pedro Lucas','******', 2.5);
INSERT INTO USUARIO VALUES(NULL,'Julia Lima','******', 2.5);
INSERT INTO USUARIO VALUES(NULL,'Carlos Augusto','******', 2.5);


CREATE TABLE CONTEUDO(
	ID_CONTEUDO INT PRIMARY KEY AUTO_INCREMENT,
	CONTEUDO VARCHAR(100),
	NOTA FLOAT(5,5)	
	
);

INSERT INTO CONTEUDO VALUES(NULL,'VIDEO AULA 1');
INSERT INTO CONTEUDO VALUES(NULL,'VIDEO AULA 2');
INSERT INTO CONTEUDO VALUES(NULL,'ARTIGO 1');
INSERT INTO CONTEUDO VALUES(NULL,'ARTIGO 2');
INSERT INTO CONTEUDO VALUES(NULL,'VIDEO AULA 3');