CREATE DATABASE RECOMENDACAO;

USE RECOMENDACAO;

CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_USUARIO VARCHAR(30),
	EMAIL VARCHAR(40) UNIQUE,
	SENHA_USUARIO VARCHAR(12),
	NOTA FLOAT(5,5)
);


INSERT INTO USUARIO VALUES(NULL,'Ana Claudia', 'claudia@email.com', '******', 2.5);
INSERT INTO USUARIO VALUES(NULL,'jorge', 'jorge@email.com', '******', 4.5);
INSERT INTO USUARIO VALUES(NULL,'maria', 'maria@email.com', '******', 3.5);
INSERT INTO USUARIO VALUES(NULL,'augusto', 'augusto@email.com', '******', 4.5);
INSERT INTO USUARIO VALUES(NULL,'luiz', 'luiz@email.com', '******', 2);
INSERT INTO USUARIO VALUES(NULL,'laura', 'laura@email.com', '******', 3);



--A CARDINALIDADE É AQUI
CREATE TABLE CONTEUDO(
	IDCONTEUDO INT PRIMARY KEY AUTO_INCREMENT,
	CONTEUDO VARCHAR(100),
	NOTA FLOAT(5,5),
	ID_USUARIO INT,
	FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO (IDUSUARIO)	
	
);

INSERT INTO CONTEUDO VALUES(NULL,'VIDEO AULA 1', 4.5, 1);
INSERT INTO CONTEUDO VALUES(NULL,'VIDEO AULA 2', 5, 2);
INSERT INTO CONTEUDO VALUES(NULL,'VIDEO AULA 3', 4.4, 3);
INSERT INTO CONTEUDO VALUES(NULL,'VIDEO AULA 4', 3, 4);
INSERT INTO CONTEUDO VALUES(NULL,'VIDEO AULA 5', 2.5, 5);